include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MusicPlayerControlsColorSettings

MusicPlayerControlsColorSettings_FILES = MPCCRootListController.m
MusicPlayerControlsColorSettings_FRAMEWORKS = UIKit
MusicPlayerControlsColorSettings_PRIVATE_FRAMEWORKS = Preferences
MusicPlayerControlsColorSettings_INSTALL_PATH = /Library/PreferenceBundles
MusicPlayerControlsColorSettings_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
